# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "0afzn0k376vw52cg2zf4z0nwxikl5dxpfxgnlx0hvl8wn0ix88jm";
    armv7l-linux = "0zwkksq8hawq3kidhwir1b45aa8nwpmcihmjzjwsjlj42limdjm5";
    aarch64-linux = "00hzs2ffxipnbddxlvgk6k5iw5pv3r9zjh28gzx1mclhlajnqm68";
    x86_64-darwin = "0ccjzykdavcbbw3fg7n3rdw5srg939zgb7yn530nvp460zcsiwgy";
    aarch64-darwin = "1wrh7dnciimci0bzc7scsgcpzizdxsqf790rfyzcxvia33s6q8m0";
  };

  urlMap = {
    x86_64-linux = "https://github.com/bab-sh/bab/releases/download/v0.8.2/bab_0.8.2_Linux_x86_64.tar.gz";
    armv7l-linux = "https://github.com/bab-sh/bab/releases/download/v0.8.2/bab_0.8.2_Linux_armv7.tar.gz";
    aarch64-linux = "https://github.com/bab-sh/bab/releases/download/v0.8.2/bab_0.8.2_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/bab-sh/bab/releases/download/v0.8.2/bab_0.8.2_macOS_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/bab-sh/bab/releases/download/v0.8.2/bab_0.8.2_macOS_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "bab";
  version = "0.8.2";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin
    cp -vr bab $out/bin/bab
    installShellCompletion --cmd bab \
    --bash completions/bab.bash \
    --zsh completions/bab.zsh \
    --fish completions/bab.fish
    mkdir -p $out/share/doc/bab
    cp -v README.md $out/share/doc/bab/README.md
    cp -v LICENSE $out/share/doc/bab/LICENSE
    runHook postInstall
  '';

  meta = {
    description = "Task runner for defining project commands in YAML";
    homepage = "https://github.com/bab-sh/bab";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv7l-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
