# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "03rvfs6429qka0dafjwq5r6m7bbi507d5pwxrqih91ki1803s44g";
    armv7l-linux = "1km04zvydd1a1yanzzixbdkp20r3x3n0nd7xxbylvasmk9dn77zc";
    aarch64-linux = "0p73gkiiq74ww4zc5k56xwwmx6w0wsrahvfing3y9wrk7qrxd3dw";
    x86_64-darwin = "1wfx4mgiv2zzh6ngcagfdprs8pr2hip0w1w315r10lpysk8zq3ds";
    aarch64-darwin = "1v5035l7hcfr6gpxjrrmf0rzbvy42hv5ckadg6rygiw23ddggikw";
  };

  urlMap = {
    x86_64-linux = "https://github.com/bab-sh/bab/releases/download/v0.8.0/bab_0.8.0_Linux_x86_64.tar.gz";
    armv7l-linux = "https://github.com/bab-sh/bab/releases/download/v0.8.0/bab_0.8.0_Linux_armv7.tar.gz";
    aarch64-linux = "https://github.com/bab-sh/bab/releases/download/v0.8.0/bab_0.8.0_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/bab-sh/bab/releases/download/v0.8.0/bab_0.8.0_macOS_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/bab-sh/bab/releases/download/v0.8.0/bab_0.8.0_macOS_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "bab";
  version = "0.8.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr bab $out/bin/bab
    installShellCompletion --cmd bab \
    --bash completions/bab.bash \
    --zsh completions/bab.zsh \
    --fish completions/bab.fish
    mkdir -p $out/share/doc/bab
    cp -v README.md $out/share/doc/bab/README.md
    cp -v LICENSE $out/share/doc/bab/LICENSE
  '';

  meta = {
    description = "Task runner for defining project commands in YAML";
    homepage = "https://github.com/bab-sh/bab";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv7l-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
