# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "0shawslr8ccwh2j09pa1azkwryqx2cmdmqy5d3gbplji8wa460vb";
    armv7l-linux = "0l0gl6c60xnjmkqggxf0r289wrg2mmg5p3wi0yf21llqjxrbcjfg";
    aarch64-linux = "0457m9a58jdjknlyc1358vb7drl9gz4zw1518avzdplmzsaw3lb4";
    x86_64-darwin = "1h8nw5qvfcrqx8xbn6cvn55hkw83wv9mv01pjygmrngyqr533y5f";
    aarch64-darwin = "1kpfljcny94hfymyrv2lwr18x50gl8655yxwalpnhddixzd336hs";
  };

  urlMap = {
    x86_64-linux = "https://github.com/bab-sh/bab/releases/download/v0.8.1/bab_0.8.1_Linux_x86_64.tar.gz";
    armv7l-linux = "https://github.com/bab-sh/bab/releases/download/v0.8.1/bab_0.8.1_Linux_armv7.tar.gz";
    aarch64-linux = "https://github.com/bab-sh/bab/releases/download/v0.8.1/bab_0.8.1_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/bab-sh/bab/releases/download/v0.8.1/bab_0.8.1_macOS_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/bab-sh/bab/releases/download/v0.8.1/bab_0.8.1_macOS_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "bab";
  version = "0.8.1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr bab $out/bin/bab
    installShellCompletion --cmd bab \
    --bash completions/bab.bash \
    --zsh completions/bab.zsh \
    --fish completions/bab.fish
    mkdir -p $out/share/doc/bab
    cp -v README.md $out/share/doc/bab/README.md
    cp -v LICENSE $out/share/doc/bab/LICENSE
  '';

  meta = {
    description = "Task runner for defining project commands in YAML";
    homepage = "https://github.com/bab-sh/bab";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv7l-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
